name: plant_pal
description: A plant care reminder app.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.10.0
  cloud_firestore: ^4.8.0
  flutter_local_notifications: ^16.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
